version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Deploy to netlify
          command: curl -X POST -d {} https://api.netlify.com/build_hooks/5fde79532c063c1d6914dec1

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - build
